export const LIQUIDATION_POSITIONS_DATA = [
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
  {
    totalBorrowed: 2062.34,
    borrowedAsset: ['XTZ', 'tzBTC'],
    collateralAsset: ['USDc', 'tzBTC'],
    healthFactor: 1.04,
    borrowerAddress: 'tz3QT9dHYKDqh563chVa6za8526ys1UKfRfL',
  },
];
